# Site Settings
title: "Yicong (Alan) Zheng"
description: "AI Research Scientist at Astera Institute with PhD in Psychology/Computational Cognitive Neuroscience"
url: https://zycyc.github.io
baseurl: ""
repository: "zycyc/zycyc.github.io"

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
  - _posts
  - _talks
  - _teaching
  - _drafts
  - markdown_generator
  - talkmap
  - talkmap.py
  - talkmap.ipynb

# Keep files
keep_files:
  - .git
  - images
  - files

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap